### PR TITLE
Upgrade dependencies to work with xcode 11.4 + #1831

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes https://github.com/AlphaWallet/alpha-wallet-ios/issues/1831

### CODE REVIEW

**Comment by hboon** [comment]
Why does it contain so many new commits?

**Comment by vladyslav-iosdev** [comment]
> Why does it contain so many new commits?

i did pretty the same as usual, 
added remote source repo and rebased master branch

**Comment by vladyslav-iosdev** [comment]
@hboon maybe i did it in wrong way?

**Comment by hboon** [comment]
> Because exyte/Macaw contains +82 commits i dont know how to squash them into single commit, (because of conflicts)

Oh. Maybe you pulled from the original source remote/repo `exyte/Macaw`? Our fork `AlphaWallet/Macaw` is based on an older version of it and we haven't kept it in sync. So we shouldn't pull from the remote `exyte/Macaw`. 

if that's the case, here's what we should do instead:

exyte/Macaw has commits A, B, C, D

AlphaWallet/Macaw has commits A, B, C, D and E

What you want to do is make a PR which contains:

Commits A, B, C, D and E and F. (F is the one where you address the issue).

Ignore `exyte/Macaw` unless there's things you want to "pull" from it. I'd rather we not sync up with `exyte/Macaw` unless there's a good reason to. It's only used in 1 part of the app, but it's quite delicate and hard to test that it doesn't break (we don't have a good collection of PDFs to test again).

**Comment by vladyslav-iosdev** [comment]
> > Because exyte/Macaw contains +82 commits i dont know how to squash them into single commit, (because of conflicts)
> 
> Oh. Maybe you pulled from the original source remote/repo `exyte/Macaw`? Our fork `AlphaWallet/Macaw` is based on an older version of it and we haven't kept it in sync. So we shouldn't pull from the remote `exyte/Macaw`.
> 
> if that's the case, here's what we should do instead:
> 
> exyte/Macaw has commits A, B, C, D
> 
> AlphaWallet/Macaw has commits A, B, C, D and E
> 
> What you want to do is make a PR which contains:
> 
> Commits A, B, C, D and E and F. (F is the one where you address the issue).
> 
> Ignore `exyte/Macaw` unless there's things you want to "pull" from it. I'd rather we not sync up with `exyte/Macaw` unless there's a good reason to. It's only used in 1 part of the app, but it's quite delicate and hard to test that it doesn't break (we don't have a good collection of PDFs to test again).

@hboon if i don't need to pull from origin remote repo, what does it mean to update dependencies?

**Pull request closed without merging**
